name: Node.js CI with SonarQube

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

    sonarqube:
        runs-on: ubuntu-latest

        needs: build

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up SonarQube
          uses: sonarsource/setup-sonarqube@v1
          with:
            sonarqube-url: ${{ secrets.SONAR_HOST_URL }}
            sonarqube-token: ${{ secrets.SONAR_TOKEN }}

        - name: Run SonarQube Scan
          run: sonar-scanner

        - name: Check SonarQube Quality Gate
          run: sonar-quality-gate-check
